- name: make directory for unix sockets
  file: path={{ SOCKET_DIR }} state=directory

- name: change ownership
  shell: chown www-data:www-data {{ SOCKET_DIR }}

- name: make directory for upstart logging
  file: path={{ LOG_DIR }} state=directory

- name: change ownership
  shell: chown www-data:www-data {{ LOG_DIR }}

- name: remove old log file
  file: path={{ LOG_DIR }}/git_commit_service.log state=absent

- name: make directory for unix sockets
  file: path={{ CONFIG_DIR }} state=directory

- name: remove old conf file
  file: path=/etc/init/git_commit_service.conf state=absent

- name: create conf file
  template: src=git_commit_service.conf.j2 dest=/etc/init/git_commit_service.conf

- name: remove old ini file
  file: path={{ CONFIG_DIR }}/git_commit_service.ini state=absent

- name: create init file
  template: src=git_commit_service.ini.j2 dest={{ CONFIG_DIR }}/git_commit_service.ini

- name: stop uwsgi
  shell: service {{ BACKEND_APP_NAME }} stop
  ignore_errors: yes

- name: start uwsgi
  shell: service {{ BACKEND_APP_NAME }} start