- name: make directory for unix sockets
  shell: mkdir {{ SOCKET_DIR }}
  ignore_errors: yes

- name: change ownership
  shell: chown www-data:www-data {{ SOCKET_DIR }}

- name: create directory for logs
  shell: mkdir {{ LOG_DIR }}
  ignore_errors: yes

- name: change ownership
  shell: chown www-data:www-data {{ LOG_DIR }}

- name: create directory for configs
  shell: mkdir {{ CONFIG_DIR }}
  ignore_errors: yes

- name: remove conf file
  shell: rm /etc/init/git_commit_service.conf
  ignore_errors: yes

- name: create conf file
  template: src=git_commit_service.conf.j2 dest=/etc/init/git_commit_service.conf

- name: remove ini file
  shell: rm {{ CONFIG_DIR }}/git_commit_service.ini
  ignore_errors: yes

- name: create init file
  template: src=git_commit_service.ini.j2 dest={{ CONFIG_DIR }}/git_commit_service.ini

- name: stop uwsgi
  shell: service {{ BACKEND_APP_NAME }} stop
  ignore_errors: yes

- name: start uwsgi
  shell: service {{ BACKEND_APP_NAME }} start