---

- hosts: backend_nodes
  sudo: true
  user: manager
  roles:
    - copy_git_service
    - libgit_install
    - backend_install
    - copy_cluster
    - cluster_install
    - cluster_config
    - backend_upstart
    - uwsgi
