- name: install git
  apt: name=git update_cache=yes

- name: remove old master project
  file: path=~/{{ CLUSTER_APP_NAME }} state=absent

- name: clone master url
  git: repo={{ CLUSTER_URL }} dest=~/{{ CLUSTER_APP_NAME }}