- name: download sbt
  get_url: url=https://dl.bintray.com/sbt/debian/sbt-0.13.6.deb dest=/tmp/sbt.deb

- name: install sbt
  shell: dpkg -i /tmp/sbt.deb

- name: update sbt
  apt: name=sbt update_cache=yes

- name: copy application.conf for backend
  template: src=application.conf.j2 dest=~/{{ MASTER_APP_NAME }}/backend/src/main/resources/application.conf