### This must be done before installing pygit (in the install role) ###
- name: download libgit2
  shell: wget https://github.com/libgit2/libgit2/archive/v0.21.1.tar.gz chdir=/usr/local/lib

- name: install cmake
  apt: name=cmake update_cache=yes

- name: unzip libgit2
  shell: tar zxf v0.21.1.tar.gz chdir=/usr/local/lib

- name: remove tar file
  shell: rm -rf v0.21.1.tar.gz chdir=/usr/local/lib

- name: cmake
  shell: cmake . chdir=/usr/local/lib/libgit2-0.21.1/

- name: make
  shell: make chdir=/usr/local/lib/libgit2-0.21.1/

- name: make install
  shell: make install chdir=/usr/local/lib/libgit2-0.21.1/

- name: fix linker
  shell: ldconfig