- name: apt-get install openjdk-7-jdk
  apt: name=openjdk-7-jdk update_cache=yes

- name: download sbt
  get_url: url=https://dl.bintray.com/sbt/debian/sbt-0.13.6.deb dest=/tmp/sbt.deb

- name: install sbt
  shell: dpkg -i /tmp/sbt.deb

- name: update sbt
  apt: name=sbt update_cache=yes