- name: add apt-key for mongodb
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

- name: create a list file for MongoDB
  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

- name: apt-get install mongodb
  apt: name=mongodb-org update_cache=yes

- name: install packages
  action: apt pkg={{item}} state=installed
  with_items:
  - python-pip
  - python-dev
  - build-essential
  - libffi-dev
  - libssl-dev
  - pkg-config
  - openjdk-7-jdk

- name: install virtualenv
  pip: name=virtualenv

- name: install uwsgi
  pip: name=uwsgi

- name: install python packages from requirements.txt
  pip: requirements=~/{{ BACKEND_APP_NAME }}/requirements.txt virtualenv=~/{{ BACKEND_APP_NAME }}/env