- name: install packages
  action: apt pkg={{item}} state=installed
  with_items:
  - ansible
  - sshpass

- name: clone backend url
  git: repo={{ GIT_SERVICE_URL }} dest=~/{{ BACKEND_APP_NAME }}
  sudo: true

- name: clone master url
  git: repo={{ CLUSTER_URL }} dest=~/{{ MASTER_APP_NAME }}

- name: create ssh password file
  template: src=ssh_pass.j2 dest=~/ssh_pass

- name: generate ssh key
  shell: ssh-keygen -q -t rsa -b 2048 -f ~/cluster -N ""
  ignore_errors: yes

#- name: rename private key to pem
#  command: mv ~/cluster ~/cluster.pem

